In [2]:
import pandas as pd

df=pd.read_excel("Ch1_Q27_V16_Data_File.xlsx")

df

,Individual,Income,Age,Sex,Married,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,1,87,46,F,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,97,52,M,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,44,25,F,Y,NaN,NaN,a. Count the number of males and females in th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,115,53,F,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,73,37,M,Y,NaN,NaN,NaN,Number of male,?,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,94,48,M,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,887,93,46,F,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,888,110,53,F,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,889,56,34,F,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,890,69,44,F,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df=df.iloc[:,:5]
df

     Individual  Income  Age Sex Married
0             1      87   46   F       Y
1             2      97   52   M       Y
2             3      44   25   F       Y
3             4     115   53   F       Y
4             5      73   37   M       Y
..          ...     ...  ...  ..     ...
885         886      94   48   M       Y
886         887      93   46   F       Y
887         888     110   53   F       N
888         889      56   34   F       Y
889         890      69   44   F       N

[890 rows x 5 columns]

In [4]:
num_males = df[df['Sex'] == 'M']['Individual'].count()
num_females = df[df['Sex'] == 'F']['Individual'].count()


total_males = num_males
total_females = num_females

num_married_males = df[(df['Sex'] == 'M') & (df['Married'] == 'Y')]['Individual'].count()
num_married_females = df[(df['Sex'] == 'F') & (df['Married'] == 'Y')]['Individual'].count()

percentage_married_males = (num_married_males / total_males) * 100
percentage_married_females = (num_married_females / total_females) * 100


top_10_highest_income = df.nlargest(10, 'Income')
num_married_males_top_10 = top_10_highest_income[(top_10_highest_income['Sex'] == 'M') & (top_10_highest_income['Married'] == 'Y')]['Individual'].count()


print("a. Number of males:", num_males)
print("   Number of females:", num_females)
print("b. Percentage of married males:", round(percentage_married_males, 2), "%")
print("   Percentage of married females:", round(percentage_married_females, 2), "%")
print("c. Number of married males among the 10 individuals with the highest income:", num_married_males_top_10)

a. Number of males: 507
   Number of females: 383
b. Percentage of married males: 66.07 %
   Percentage of married females: 65.01 %
c. Number of married males among the 10 individuals with the highest income: 7